/** 獨立店名用詞，組出不重複商戶，不用品牌編號變體。 */
export const MERCHANT_NAME_PREFIXES = [
  'Amber',
  'Atlas',
  'Aurora',
  'Beacon',
  'Birch',
  'Bluebird',
  'Cedar',
  'Cinder',
  'Cobalt',
  'Copper',
  'Coral',
  'Crimson',
  'Cypress',
  'Dawn',
  'Drift',
  'Ember',
  'Fern',
  'Flint',
  'Fog',
  'Forge',
  'Frost',
  'Garden',
  'Glen',
  'Golden',
  'Granite',
  'Harbor',
  'Hazel',
  'Heather',
  'Hollow',
  'Honey',
  'Ivory',
  'Jade',
  'Juniper',
  'Lake',
  'Lark',
  'Laurel',
  'Linden',
  'Lotus',
  'Maple',
  'Marble',
  'Meadow',
  'Mercury',
  'Mosaic',
  'Nimbus',
  'North',
  'Oak',
  'Olive',
  'Orchid',
  'Osprey',
  'Pacific',
  'Pearl',
  'Pebble',
  'Pine',
  'Prairie',
  'Quill',
  'Raven',
  'Redwood',
  'River',
  'Saffron',
  'Sage',
  'Silver',
  'Sparrow',
  'Spruce',
  'Stone',
  'Summit',
  'Thistle',
  'Tide',
  'Timber',
  'Violet',
  'Willow',
  'Wren',
  'Yarrow'
] as const

export const MERCHANT_NAME_CORES = [
  'Alley',
  'Anchor',
  'Arcade',
  'Atelier',
  'Barn',
  'Bazaar',
  'Bistro',
  'Bridge',
  'Cabin',
  'Canal',
  'Canyon',
  'Cart',
  'Cellar',
  'Chapel',
  'Commons',
  'Cove',
  'Cross',
  'Depot',
  'Dock',
  'Dome',
  'Field',
  'Fjord',
  'Gate',
  'Grove',
  'Hall',
  'Haven',
  'Hill',
  'House',
  'Hut',
  'Isle',
  'Keep',
  'Lane',
  'Loft',
  'Mill',
  'Nook',
  'Orchard',
  'Outlet',
  'Overlook',
  'Park',
  'Pass',
  'Patio',
  'Pier',
  'Plaza',
  'Point',
  'Port',
  'Post',
  'Quay',
  'Ridge',
  'Road',
  'Room',
  'Row',
  'Shed',
  'Shore',
  'Square',
  'Stall',
  'Station',
  'Studio',
  'Terrace',
  'Trail',
  'Valley',
  'Vault',
  'View',
  'Village',
  'Walk',
  'Wharf',
  'Yard',
  'Quarter',
  'Corner',
  'Court',
  'Garden'
] as const

export type MerchantKind = { suffix: string; mcc: string }

export const MERCHANT_KINDS: readonly MerchantKind[] = [
  { suffix: 'Cafe', mcc: '5812' },
  { suffix: 'Kitchen', mcc: '5814' },
  { suffix: 'Bakery', mcc: '5462' },
  { suffix: 'Grocery', mcc: '5411' },
  { suffix: 'Market', mcc: '5499' },
  { suffix: 'Pharmacy', mcc: '5912' },
  { suffix: 'Books', mcc: '5942' },
  { suffix: 'Apparel', mcc: '5651' },
  { suffix: 'Boutique', mcc: '5691' },
  { suffix: 'Shoes', mcc: '5661' },
  { suffix: 'Electronics', mcc: '5732' },
  { suffix: 'Furniture', mcc: '5712' },
  { suffix: 'Hotel', mcc: '7011' },
  { suffix: 'Inn', mcc: '7011' },
  { suffix: 'Rides', mcc: '4121' },
  { suffix: 'Fuel', mcc: '5541' },
  { suffix: 'Hardware', mcc: '5251' },
  { suffix: 'Florist', mcc: '5992' },
  { suffix: 'Sports', mcc: '5941' },
  { suffix: 'Cinema', mcc: '7832' }
]
